/*********************************************************************/
/* Simon Game - Pattern Generator Logic                              */
/*********************************************************************/


// This array will store the sequence generated by the game.
// Example after 3 rounds: ["red", "blue", "green"]
var gamePattern = [];


// This array contains all the possible button colours.
// These match the IDs of your buttons in the HTML.
var buttonColours = ["red", "blue", "green", "yellow"];



/*********************************************************************/
/* Start the game when any key is pressed                            */
/*********************************************************************/

// jQuery event listener attached to the entire document.
// When the user presses any key on the keyboard,
// the function nextSequence() will run.
$(document).keypress(function () {
    nextSequence();
});



/*********************************************************************/
/* Function: nextSequence()                                          */
/* Purpose:                                                           */
/* 1. Generate a random number (0–3)                                  */
/* 2. Pick a colour based on that number                              */
/* 3. Add that colour to gamePattern                                  */
/* 4. Animate the selected button                                     */
/* 5. Play the corresponding sound                                     */
/*********************************************************************/

function nextSequence() {

    // -------------------------------------------------------------
    // STEP 1: Generate a random number between 0 and 3
    // Math.random() gives a number from 0 to 0.999...
    // Multiplying by 4 gives 0 to 3.999...
    // Math.floor() converts it to 0, 1, 2, or 3
    // -------------------------------------------------------------
    var randomNumber = Math.floor(Math.random() * 4);


    // -------------------------------------------------------------
    // STEP 2: Select a colour using the random number as index
    // Example:
    // If randomNumber = 2
    // buttonColours[2] = "green"
    // -------------------------------------------------------------
    var randomChosenColour = buttonColours[randomNumber];


    // -------------------------------------------------------------
    // STEP 3: Add the new colour to the gamePattern array
    // This builds the memory sequence step by step
    // -------------------------------------------------------------
    gamePattern.push(randomChosenColour);


    // -------------------------------------------------------------
    // Debugging: print the newly chosen colour in the console
    // Useful during development
    // -------------------------------------------------------------
    console.log("New Colour Added:", randomChosenColour);
    console.log("Current Pattern:", gamePattern);


    // -------------------------------------------------------------
    // STEP 4: Animate the selected button
    // $("#" + randomChosenColour)
    // If colour = "red"
    // It becomes: $("#red")
    //
    // fadeOut(100) -> disappear in 100ms
    // fadeIn(100)  -> appear again in 100ms
    // -------------------------------------------------------------
    $("#" + randomChosenColour)
        .fadeOut(100)
        .fadeIn(100);


    // -------------------------------------------------------------
    // STEP 5: Play the sound for that button
    // It dynamically builds the file path:
    // Example:
    // "sounds/red.mp3"
    // "sounds/blue.mp3"
    // -------------------------------------------------------------
    var audio = new Audio("sounds/" + randomChosenColour + ".mp3");
    audio.play();
}
