/*********************************************************************/
/* Simon Game - Pattern Generator Logic                              */
/*********************************************************************/


// This array will store the sequence generated by the game.
// Example after 3 rounds: ["red", "blue", "green"]
var gamePattern = [];


// This array contains all the possible button colours.
// These match the IDs of your buttons in the HTML.
var buttonColours = ["red", "blue", "green", "yellow"];



/*********************************************************************/
/* Game Start + Level System                                         */
/*********************************************************************/

// Track game state
var started = false;   // To make sure game starts only once
var level = 0;         // Game level starts at 0


// Detect first keypress to start game
$(document).keydown(function () {

    // If game hasn't started yet
    if (!started) {

        $("#level-title").text("Level " + level);

        nextSequence();

        started = true; // Prevent restarting on every key press
    }

});



/*********************************************************************/
/* Function: nextSequence()                                          */
/* Purpose:                                                           */
/* 1. Generate a random number (0–3)                                  */
/* 2. Pick a colour based on that number                              */
/* 3. Add that colour to gamePattern                                  */
/* 4. Animate the selected button                                     */
/* 5. Play the corresponding sound                                     */
/*********************************************************************/

function nextSequence() {

    // Increase level each time new sequence is generated
    level++;

    // Update the h1 text with new level
    $("#level-title").text("Level " + level);

    // -------------------------------------------------------------
    // STEP 1: Generate a random number between 0 and 3
    // Math.random() gives a number from 0 to 0.999...
    // Multiplying by 4 gives 0 to 3.999...
    // Math.floor() converts it to 0, 1, 2, or 3
    // -------------------------------------------------------------
    var randomNumber = Math.floor(Math.random() * 4);


    // -------------------------------------------------------------
    // STEP 2: Select a colour using the random number as index
    // Example:
    // If randomNumber = 2
    // buttonColours[2] = "green"
    // -------------------------------------------------------------
    var randomChosenColour = buttonColours[randomNumber];


    // -------------------------------------------------------------
    // STEP 3: Add the new colour to the gamePattern array
    // This builds the memory sequence step by step
    // -------------------------------------------------------------
    gamePattern.push(randomChosenColour);


    // -------------------------------------------------------------
    // Debugging: print the newly chosen colour in the console
    // Useful during development
    // -------------------------------------------------------------
    console.log("New Colour Added:", randomChosenColour);
    console.log("Current Pattern:", gamePattern);


    // -------------------------------------------------------------
    // STEP 4: Animate the selected button
    // $("#" + randomChosenColour)
    // If colour = "red"
    // It becomes: $("#red")
    //
    // fadeOut(100) -> disappear in 100ms
    // fadeIn(100)  -> appear again in 100ms
    // -------------------------------------------------------------
    $("#" + randomChosenColour)
        .fadeOut(100)
        .fadeIn(100);


    // Play sound using reusable function
    playSound(randomChosenColour);

    // -------------------------------------------------------------
    // STEP 5: Play the sound for that button
    // It dynamically builds the file path:
    // Example:
    // "sounds/red.mp3"
    // "sounds/blue.mp3"
    // -------------------------------------------------------------
    // var audio = new Audio("sounds/" + randomChosenColour + ".mp3");
    // audio.play();
}

/*********************************************************************/
/* User Click Detection Logic                                        */
/*********************************************************************/

// Store the colours clicked by the user
var userClickedPattern = [];


// Detect when any button with class "btn" is clicked
$(".btn").click(function () {

    // 1 Get the id of the clicked button
    // "this" refers to the button that was clicked
    // Example: if green button clicked → "green"
    var userChosenColour = $(this).attr("id");

    // 2 Add the clicked colour to userClickedPattern array
    userClickedPattern.push(userChosenColour);

    // Play sound using same function
    playSound(userChosenColour);

    // Debug: check if pattern builds correctly
    console.log(userClickedPattern);

    //  Add button press animation
    animatePress(userChosenColour);

});


/*********************************************************************/
/* Function: playSound(name)                                         */
/* Purpose: Play sound based on button colour                        */
/*********************************************************************/

function playSound(name) {

    // Build the file path dynamically
    // Example: name = "green"
    // → "sounds/green.mp3"
    var audio = new Audio("sounds/" + name + ".mp3");

    // Play the sound
    audio.play();
}

/*********************************************************************/
/* Function: animatePress(currentColour)                             */
/* Purpose: Add "pressed" effect to clicked button briefly           */
/*********************************************************************/

function animatePress(currentColour) {
    // Add Debug Log Inside animatePress()
    console.log("Animating:", currentColour);

    // Select the button using its id
    // Example: currentColour = "green"
    // → $("#green")
    $("#" + currentColour).addClass("pressed");

    // Remove the class after 100 milliseconds
    // setTimeout runs a function after a delay
    setTimeout(function () {

        $("#" + currentColour).removeClass("pressed");

    }, 100); // 100ms delay
}