
// Stores the sequence generated by the game
var gamePattern = [];

// Available button colours (match HTML button IDs)
var buttonColours = ["red", "blue", "green", "yellow"];


// Start game when any key is pressed
$(document).keypress(function () {
    nextSequence();
});


function nextSequence() {

    // 1 Generate random number (0–3)
    // Math.random() → 0–3.999 → Math.floor() → 0,1,2,3
    var randomNumber = Math.floor(Math.random() * 4);

    // 2 Pick colour using the random index
    var randomChosenColour = buttonColours[randomNumber];

    // 3 Add new colour to game pattern array
    gamePattern.push(randomChosenColour);

    // Debug: show pattern in console
    console.log(gamePattern);

    // 4 Flash the chosen button
    //Use jQuery to select the button with the same id as the randomChosenColour
    // Use Google/Stackoverflow to figure out how you can use jQuery to animate a flash to the button selected in step 1.
    $("#" + randomChosenColour).fadeOut(100).fadeIn(100);

    // 5 Play matching sound
    var audio = new Audio("sounds/" + randomChosenColour + ".mp3");
    audio.play();
}
