
// Stores the sequence generated by the game
var gamePattern = [];

// Available button colours (match HTML button IDs)
var buttonColours = ["red", "blue", "green", "yellow"];

/*********************************************************************/
/* Start the game when any key is pressed                            */
/*********************************************************************/

// Start game when any key is pressed
$(document).keypress(function () {
    nextSequence();
});


function nextSequence() {

    // 1 Generate random number (0–3)
    // Math.random() → 0–3.999 → Math.floor() → 0,1,2,3
    var randomNumber = Math.floor(Math.random() * 4);

    // 2 Pick colour using the random index
    var randomChosenColour = buttonColours[randomNumber];

    // 3 Add new colour to game pattern array
    gamePattern.push(randomChosenColour);

    // Debug: show pattern in console
    console.log(gamePattern);

    // 4 Flash the chosen button
    //Use jQuery to select the button with the same id as the randomChosenColour
    // Use Google/Stackoverflow to figure out how you can use jQuery to animate a flash to the button selected in step 1.
    $("#" + randomChosenColour).fadeOut(100).fadeIn(100);

    // Play sound using same function
    playSound(randomChosenColour);

    // 5 Play matching sound
    // var audio = new Audio("sounds/" + randomChosenColour + ".mp3");
    // audio.play();
}

/*********************************************************************/
/* User Click Detection Logic                                        */
/*********************************************************************/

// Store the colours clicked by the user
var userClickedPattern = [];


// Detect when any button with class "btn" is clicked
$(".btn").click(function () {

    // 1 Get the id of the clicked button
    // "this" refers to the button that was clicked
    // Example: if green button clicked → "green"
    var userChosenColour = $(this).attr("id");

    // 2 Add the clicked colour to userClickedPattern array
    userClickedPattern.push(userChosenColour);

    // Debug: check if pattern builds correctly
    console.log(userClickedPattern);

    //  Play sound using same function
    playSound(userChosenColour);

    //  Add button press animation
    animatePress(userChosenColour);

});


/*********************************************************************/
/* Function: playSound(name)                                         */
/* Purpose: Play sound based on button colour                        */
/*********************************************************************/

function playSound(name) {

    // Build the file path dynamically
    // Example: name = "green"
    // → "sounds/green.mp3"
    var audio = new Audio("sounds/" + name + ".mp3");

    // Play the sound
    audio.play();
}

/*********************************************************************/
/* Function: animatePress(currentColour)                             */
/* Purpose: Add "pressed" effect to clicked button briefly           */
/*********************************************************************/

function animatePress(currentColour) {
    // Add Debug Log Inside animatePress()
    console.log("Animating:", currentColour);
    
    // Select the button using its id
    // Example: currentColour = "green"
    // → $("#green")
    $("#" + currentColour).addClass("pressed");

    // Remove the class after 100 milliseconds
    // setTimeout runs a function after a delay
    setTimeout(function () {

        $("#" + currentColour).removeClass("pressed");

    }, 100); // 100ms delay
}